# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/finian/Documents/git/openglgame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/finian/Documents/git/openglgame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/finian/Documents/git/openglgame/CMakeFiles /home/finian/Documents/git/openglgame/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/finian/Documents/git/openglgame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named openglgame

# Build rule for target.
openglgame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openglgame
.PHONY : openglgame

# fast build rule for target.
openglgame/fast:
	$(MAKE) -f CMakeFiles/openglgame.dir/build.make CMakeFiles/openglgame.dir/build
.PHONY : openglgame/fast

#=============================================================================
# Target rules for targets named cglm

# Build rule for target.
cglm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cglm
.PHONY : cglm

# fast build rule for target.
cglm/fast:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/build
.PHONY : cglm/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f ext/glfw/CMakeFiles/uninstall.dir/build.make ext/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f ext/glfw/src/CMakeFiles/glfw.dir/build.make ext/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

ext/cglm/src/affine.o: ext/cglm/src/affine.c.o

.PHONY : ext/cglm/src/affine.o

# target to build an object file
ext/cglm/src/affine.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/affine.c.o
.PHONY : ext/cglm/src/affine.c.o

ext/cglm/src/affine.i: ext/cglm/src/affine.c.i

.PHONY : ext/cglm/src/affine.i

# target to preprocess a source file
ext/cglm/src/affine.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/affine.c.i
.PHONY : ext/cglm/src/affine.c.i

ext/cglm/src/affine.s: ext/cglm/src/affine.c.s

.PHONY : ext/cglm/src/affine.s

# target to generate assembly for a file
ext/cglm/src/affine.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/affine.c.s
.PHONY : ext/cglm/src/affine.c.s

ext/cglm/src/bezier.o: ext/cglm/src/bezier.c.o

.PHONY : ext/cglm/src/bezier.o

# target to build an object file
ext/cglm/src/bezier.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/bezier.c.o
.PHONY : ext/cglm/src/bezier.c.o

ext/cglm/src/bezier.i: ext/cglm/src/bezier.c.i

.PHONY : ext/cglm/src/bezier.i

# target to preprocess a source file
ext/cglm/src/bezier.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/bezier.c.i
.PHONY : ext/cglm/src/bezier.c.i

ext/cglm/src/bezier.s: ext/cglm/src/bezier.c.s

.PHONY : ext/cglm/src/bezier.s

# target to generate assembly for a file
ext/cglm/src/bezier.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/bezier.c.s
.PHONY : ext/cglm/src/bezier.c.s

ext/cglm/src/box.o: ext/cglm/src/box.c.o

.PHONY : ext/cglm/src/box.o

# target to build an object file
ext/cglm/src/box.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/box.c.o
.PHONY : ext/cglm/src/box.c.o

ext/cglm/src/box.i: ext/cglm/src/box.c.i

.PHONY : ext/cglm/src/box.i

# target to preprocess a source file
ext/cglm/src/box.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/box.c.i
.PHONY : ext/cglm/src/box.c.i

ext/cglm/src/box.s: ext/cglm/src/box.c.s

.PHONY : ext/cglm/src/box.s

# target to generate assembly for a file
ext/cglm/src/box.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/box.c.s
.PHONY : ext/cglm/src/box.c.s

ext/cglm/src/cam.o: ext/cglm/src/cam.c.o

.PHONY : ext/cglm/src/cam.o

# target to build an object file
ext/cglm/src/cam.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/cam.c.o
.PHONY : ext/cglm/src/cam.c.o

ext/cglm/src/cam.i: ext/cglm/src/cam.c.i

.PHONY : ext/cglm/src/cam.i

# target to preprocess a source file
ext/cglm/src/cam.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/cam.c.i
.PHONY : ext/cglm/src/cam.c.i

ext/cglm/src/cam.s: ext/cglm/src/cam.c.s

.PHONY : ext/cglm/src/cam.s

# target to generate assembly for a file
ext/cglm/src/cam.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/cam.c.s
.PHONY : ext/cglm/src/cam.c.s

ext/cglm/src/curve.o: ext/cglm/src/curve.c.o

.PHONY : ext/cglm/src/curve.o

# target to build an object file
ext/cglm/src/curve.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/curve.c.o
.PHONY : ext/cglm/src/curve.c.o

ext/cglm/src/curve.i: ext/cglm/src/curve.c.i

.PHONY : ext/cglm/src/curve.i

# target to preprocess a source file
ext/cglm/src/curve.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/curve.c.i
.PHONY : ext/cglm/src/curve.c.i

ext/cglm/src/curve.s: ext/cglm/src/curve.c.s

.PHONY : ext/cglm/src/curve.s

# target to generate assembly for a file
ext/cglm/src/curve.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/curve.c.s
.PHONY : ext/cglm/src/curve.c.s

ext/cglm/src/ease.o: ext/cglm/src/ease.c.o

.PHONY : ext/cglm/src/ease.o

# target to build an object file
ext/cglm/src/ease.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/ease.c.o
.PHONY : ext/cglm/src/ease.c.o

ext/cglm/src/ease.i: ext/cglm/src/ease.c.i

.PHONY : ext/cglm/src/ease.i

# target to preprocess a source file
ext/cglm/src/ease.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/ease.c.i
.PHONY : ext/cglm/src/ease.c.i

ext/cglm/src/ease.s: ext/cglm/src/ease.c.s

.PHONY : ext/cglm/src/ease.s

# target to generate assembly for a file
ext/cglm/src/ease.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/ease.c.s
.PHONY : ext/cglm/src/ease.c.s

ext/cglm/src/euler.o: ext/cglm/src/euler.c.o

.PHONY : ext/cglm/src/euler.o

# target to build an object file
ext/cglm/src/euler.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/euler.c.o
.PHONY : ext/cglm/src/euler.c.o

ext/cglm/src/euler.i: ext/cglm/src/euler.c.i

.PHONY : ext/cglm/src/euler.i

# target to preprocess a source file
ext/cglm/src/euler.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/euler.c.i
.PHONY : ext/cglm/src/euler.c.i

ext/cglm/src/euler.s: ext/cglm/src/euler.c.s

.PHONY : ext/cglm/src/euler.s

# target to generate assembly for a file
ext/cglm/src/euler.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/euler.c.s
.PHONY : ext/cglm/src/euler.c.s

ext/cglm/src/frustum.o: ext/cglm/src/frustum.c.o

.PHONY : ext/cglm/src/frustum.o

# target to build an object file
ext/cglm/src/frustum.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/frustum.c.o
.PHONY : ext/cglm/src/frustum.c.o

ext/cglm/src/frustum.i: ext/cglm/src/frustum.c.i

.PHONY : ext/cglm/src/frustum.i

# target to preprocess a source file
ext/cglm/src/frustum.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/frustum.c.i
.PHONY : ext/cglm/src/frustum.c.i

ext/cglm/src/frustum.s: ext/cglm/src/frustum.c.s

.PHONY : ext/cglm/src/frustum.s

# target to generate assembly for a file
ext/cglm/src/frustum.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/frustum.c.s
.PHONY : ext/cglm/src/frustum.c.s

ext/cglm/src/io.o: ext/cglm/src/io.c.o

.PHONY : ext/cglm/src/io.o

# target to build an object file
ext/cglm/src/io.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/io.c.o
.PHONY : ext/cglm/src/io.c.o

ext/cglm/src/io.i: ext/cglm/src/io.c.i

.PHONY : ext/cglm/src/io.i

# target to preprocess a source file
ext/cglm/src/io.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/io.c.i
.PHONY : ext/cglm/src/io.c.i

ext/cglm/src/io.s: ext/cglm/src/io.c.s

.PHONY : ext/cglm/src/io.s

# target to generate assembly for a file
ext/cglm/src/io.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/io.c.s
.PHONY : ext/cglm/src/io.c.s

ext/cglm/src/mat2.o: ext/cglm/src/mat2.c.o

.PHONY : ext/cglm/src/mat2.o

# target to build an object file
ext/cglm/src/mat2.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/mat2.c.o
.PHONY : ext/cglm/src/mat2.c.o

ext/cglm/src/mat2.i: ext/cglm/src/mat2.c.i

.PHONY : ext/cglm/src/mat2.i

# target to preprocess a source file
ext/cglm/src/mat2.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/mat2.c.i
.PHONY : ext/cglm/src/mat2.c.i

ext/cglm/src/mat2.s: ext/cglm/src/mat2.c.s

.PHONY : ext/cglm/src/mat2.s

# target to generate assembly for a file
ext/cglm/src/mat2.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/mat2.c.s
.PHONY : ext/cglm/src/mat2.c.s

ext/cglm/src/mat3.o: ext/cglm/src/mat3.c.o

.PHONY : ext/cglm/src/mat3.o

# target to build an object file
ext/cglm/src/mat3.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/mat3.c.o
.PHONY : ext/cglm/src/mat3.c.o

ext/cglm/src/mat3.i: ext/cglm/src/mat3.c.i

.PHONY : ext/cglm/src/mat3.i

# target to preprocess a source file
ext/cglm/src/mat3.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/mat3.c.i
.PHONY : ext/cglm/src/mat3.c.i

ext/cglm/src/mat3.s: ext/cglm/src/mat3.c.s

.PHONY : ext/cglm/src/mat3.s

# target to generate assembly for a file
ext/cglm/src/mat3.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/mat3.c.s
.PHONY : ext/cglm/src/mat3.c.s

ext/cglm/src/mat4.o: ext/cglm/src/mat4.c.o

.PHONY : ext/cglm/src/mat4.o

# target to build an object file
ext/cglm/src/mat4.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/mat4.c.o
.PHONY : ext/cglm/src/mat4.c.o

ext/cglm/src/mat4.i: ext/cglm/src/mat4.c.i

.PHONY : ext/cglm/src/mat4.i

# target to preprocess a source file
ext/cglm/src/mat4.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/mat4.c.i
.PHONY : ext/cglm/src/mat4.c.i

ext/cglm/src/mat4.s: ext/cglm/src/mat4.c.s

.PHONY : ext/cglm/src/mat4.s

# target to generate assembly for a file
ext/cglm/src/mat4.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/mat4.c.s
.PHONY : ext/cglm/src/mat4.c.s

ext/cglm/src/plane.o: ext/cglm/src/plane.c.o

.PHONY : ext/cglm/src/plane.o

# target to build an object file
ext/cglm/src/plane.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/plane.c.o
.PHONY : ext/cglm/src/plane.c.o

ext/cglm/src/plane.i: ext/cglm/src/plane.c.i

.PHONY : ext/cglm/src/plane.i

# target to preprocess a source file
ext/cglm/src/plane.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/plane.c.i
.PHONY : ext/cglm/src/plane.c.i

ext/cglm/src/plane.s: ext/cglm/src/plane.c.s

.PHONY : ext/cglm/src/plane.s

# target to generate assembly for a file
ext/cglm/src/plane.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/plane.c.s
.PHONY : ext/cglm/src/plane.c.s

ext/cglm/src/project.o: ext/cglm/src/project.c.o

.PHONY : ext/cglm/src/project.o

# target to build an object file
ext/cglm/src/project.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/project.c.o
.PHONY : ext/cglm/src/project.c.o

ext/cglm/src/project.i: ext/cglm/src/project.c.i

.PHONY : ext/cglm/src/project.i

# target to preprocess a source file
ext/cglm/src/project.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/project.c.i
.PHONY : ext/cglm/src/project.c.i

ext/cglm/src/project.s: ext/cglm/src/project.c.s

.PHONY : ext/cglm/src/project.s

# target to generate assembly for a file
ext/cglm/src/project.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/project.c.s
.PHONY : ext/cglm/src/project.c.s

ext/cglm/src/quat.o: ext/cglm/src/quat.c.o

.PHONY : ext/cglm/src/quat.o

# target to build an object file
ext/cglm/src/quat.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/quat.c.o
.PHONY : ext/cglm/src/quat.c.o

ext/cglm/src/quat.i: ext/cglm/src/quat.c.i

.PHONY : ext/cglm/src/quat.i

# target to preprocess a source file
ext/cglm/src/quat.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/quat.c.i
.PHONY : ext/cglm/src/quat.c.i

ext/cglm/src/quat.s: ext/cglm/src/quat.c.s

.PHONY : ext/cglm/src/quat.s

# target to generate assembly for a file
ext/cglm/src/quat.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/quat.c.s
.PHONY : ext/cglm/src/quat.c.s

ext/cglm/src/sphere.o: ext/cglm/src/sphere.c.o

.PHONY : ext/cglm/src/sphere.o

# target to build an object file
ext/cglm/src/sphere.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/sphere.c.o
.PHONY : ext/cglm/src/sphere.c.o

ext/cglm/src/sphere.i: ext/cglm/src/sphere.c.i

.PHONY : ext/cglm/src/sphere.i

# target to preprocess a source file
ext/cglm/src/sphere.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/sphere.c.i
.PHONY : ext/cglm/src/sphere.c.i

ext/cglm/src/sphere.s: ext/cglm/src/sphere.c.s

.PHONY : ext/cglm/src/sphere.s

# target to generate assembly for a file
ext/cglm/src/sphere.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/sphere.c.s
.PHONY : ext/cglm/src/sphere.c.s

ext/cglm/src/vec3.o: ext/cglm/src/vec3.c.o

.PHONY : ext/cglm/src/vec3.o

# target to build an object file
ext/cglm/src/vec3.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/vec3.c.o
.PHONY : ext/cglm/src/vec3.c.o

ext/cglm/src/vec3.i: ext/cglm/src/vec3.c.i

.PHONY : ext/cglm/src/vec3.i

# target to preprocess a source file
ext/cglm/src/vec3.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/vec3.c.i
.PHONY : ext/cglm/src/vec3.c.i

ext/cglm/src/vec3.s: ext/cglm/src/vec3.c.s

.PHONY : ext/cglm/src/vec3.s

# target to generate assembly for a file
ext/cglm/src/vec3.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/vec3.c.s
.PHONY : ext/cglm/src/vec3.c.s

ext/cglm/src/vec4.o: ext/cglm/src/vec4.c.o

.PHONY : ext/cglm/src/vec4.o

# target to build an object file
ext/cglm/src/vec4.c.o:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/vec4.c.o
.PHONY : ext/cglm/src/vec4.c.o

ext/cglm/src/vec4.i: ext/cglm/src/vec4.c.i

.PHONY : ext/cglm/src/vec4.i

# target to preprocess a source file
ext/cglm/src/vec4.c.i:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/vec4.c.i
.PHONY : ext/cglm/src/vec4.c.i

ext/cglm/src/vec4.s: ext/cglm/src/vec4.c.s

.PHONY : ext/cglm/src/vec4.s

# target to generate assembly for a file
ext/cglm/src/vec4.c.s:
	$(MAKE) -f CMakeFiles/cglm.dir/build.make CMakeFiles/cglm.dir/ext/cglm/src/vec4.c.s
.PHONY : ext/cglm/src/vec4.c.s

ext/glad/src/glad.o: ext/glad/src/glad.c.o

.PHONY : ext/glad/src/glad.o

# target to build an object file
ext/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/ext/glad/src/glad.c.o
.PHONY : ext/glad/src/glad.c.o

ext/glad/src/glad.i: ext/glad/src/glad.c.i

.PHONY : ext/glad/src/glad.i

# target to preprocess a source file
ext/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/ext/glad/src/glad.c.i
.PHONY : ext/glad/src/glad.c.i

ext/glad/src/glad.s: ext/glad/src/glad.c.s

.PHONY : ext/glad/src/glad.s

# target to generate assembly for a file
ext/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/ext/glad/src/glad.c.s
.PHONY : ext/glad/src/glad.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/openglgame.dir/build.make CMakeFiles/openglgame.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/openglgame.dir/build.make CMakeFiles/openglgame.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/openglgame.dir/build.make CMakeFiles/openglgame.dir/src/main.c.s
.PHONY : src/main.c.s

src/shaderread.o: src/shaderread.c.o

.PHONY : src/shaderread.o

# target to build an object file
src/shaderread.c.o:
	$(MAKE) -f CMakeFiles/openglgame.dir/build.make CMakeFiles/openglgame.dir/src/shaderread.c.o
.PHONY : src/shaderread.c.o

src/shaderread.i: src/shaderread.c.i

.PHONY : src/shaderread.i

# target to preprocess a source file
src/shaderread.c.i:
	$(MAKE) -f CMakeFiles/openglgame.dir/build.make CMakeFiles/openglgame.dir/src/shaderread.c.i
.PHONY : src/shaderread.c.i

src/shaderread.s: src/shaderread.c.s

.PHONY : src/shaderread.s

# target to generate assembly for a file
src/shaderread.c.s:
	$(MAKE) -f CMakeFiles/openglgame.dir/build.make CMakeFiles/openglgame.dir/src/shaderread.c.s
.PHONY : src/shaderread.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... glad"
	@echo "... openglgame"
	@echo "... rebuild_cache"
	@echo "... cglm"
	@echo "... edit_cache"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... ext/cglm/src/affine.o"
	@echo "... ext/cglm/src/affine.i"
	@echo "... ext/cglm/src/affine.s"
	@echo "... ext/cglm/src/bezier.o"
	@echo "... ext/cglm/src/bezier.i"
	@echo "... ext/cglm/src/bezier.s"
	@echo "... ext/cglm/src/box.o"
	@echo "... ext/cglm/src/box.i"
	@echo "... ext/cglm/src/box.s"
	@echo "... ext/cglm/src/cam.o"
	@echo "... ext/cglm/src/cam.i"
	@echo "... ext/cglm/src/cam.s"
	@echo "... ext/cglm/src/curve.o"
	@echo "... ext/cglm/src/curve.i"
	@echo "... ext/cglm/src/curve.s"
	@echo "... ext/cglm/src/ease.o"
	@echo "... ext/cglm/src/ease.i"
	@echo "... ext/cglm/src/ease.s"
	@echo "... ext/cglm/src/euler.o"
	@echo "... ext/cglm/src/euler.i"
	@echo "... ext/cglm/src/euler.s"
	@echo "... ext/cglm/src/frustum.o"
	@echo "... ext/cglm/src/frustum.i"
	@echo "... ext/cglm/src/frustum.s"
	@echo "... ext/cglm/src/io.o"
	@echo "... ext/cglm/src/io.i"
	@echo "... ext/cglm/src/io.s"
	@echo "... ext/cglm/src/mat2.o"
	@echo "... ext/cglm/src/mat2.i"
	@echo "... ext/cglm/src/mat2.s"
	@echo "... ext/cglm/src/mat3.o"
	@echo "... ext/cglm/src/mat3.i"
	@echo "... ext/cglm/src/mat3.s"
	@echo "... ext/cglm/src/mat4.o"
	@echo "... ext/cglm/src/mat4.i"
	@echo "... ext/cglm/src/mat4.s"
	@echo "... ext/cglm/src/plane.o"
	@echo "... ext/cglm/src/plane.i"
	@echo "... ext/cglm/src/plane.s"
	@echo "... ext/cglm/src/project.o"
	@echo "... ext/cglm/src/project.i"
	@echo "... ext/cglm/src/project.s"
	@echo "... ext/cglm/src/quat.o"
	@echo "... ext/cglm/src/quat.i"
	@echo "... ext/cglm/src/quat.s"
	@echo "... ext/cglm/src/sphere.o"
	@echo "... ext/cglm/src/sphere.i"
	@echo "... ext/cglm/src/sphere.s"
	@echo "... ext/cglm/src/vec3.o"
	@echo "... ext/cglm/src/vec3.i"
	@echo "... ext/cglm/src/vec3.s"
	@echo "... ext/cglm/src/vec4.o"
	@echo "... ext/cglm/src/vec4.i"
	@echo "... ext/cglm/src/vec4.s"
	@echo "... ext/glad/src/glad.o"
	@echo "... ext/glad/src/glad.i"
	@echo "... ext/glad/src/glad.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shaderread.o"
	@echo "... src/shaderread.i"
	@echo "... src/shaderread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

